---
- name: Label control plane node as PreferNoSchedule
  become: false
  delegate_to: localhost
  kubernetes.core.k8s_taint:
    name: "{{ ansible_nodename }}"
    state: present
    taints:
    - effect: PreferNoSchedule
      key: node-role.kubernetes.io/control-plane

- name: Remove taint NoSchedule of control plane node
  become: false
  delegate_to: localhost
  kubernetes.core.k8s_taint:
    name: "{{ ansible_nodename }}"
    state: absent
    taints:
    - effect: NoSchedule
      key: node-role.kubernetes.io/control-plane
