# https://github.com/cert-manager/cert-manager/blob/v1.13.2/deploy/charts/cert-manager/values.yaml
replicaCount: 1

image:
  repository: quay.m.daocloud.io/jetstack/cert-manager-controller

affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
        - matchExpressions:
            - key: node-role.kubernetes.io/control-plane
              operator: Exists

cainjector:
  image:
    repository: quay.m.daocloud.io/jetstack/cert-manager-cainjector
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: node-role.kubernetes.io/control-plane
                operator: Exists

webhook:
  image:
    repository: quay.m.daocloud.io/jetstack/cert-manager-webhook
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: node-role.kubernetes.io/control-plane
                operator: Exists

startupapicheck:
  image:
    repository: quay.m.daocloud.io/jetstack/cert-manager-ctl
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: node-role.kubernetes.io/control-plane
                operator: Exists
