---
- name: Create harbor namespace
  run_once: true
  delegate_to: localhost
  kubernetes.core.k8s:
    name: harbor
    api_version: v1
    kind: Namespace
    state: present

- name: Check if certificates harbor-tls-cert exists
  run_once: true
  delegate_to: localhost
  ansible.builtin.shell: kubectl -n harbor get certificates.cert-manager.io harbor-tls-cert
  register: harbor_tls_cert
  ignore_errors: true
  changed_when: false

- name: Create harbor-tls-cert
  when: harbor_tls_cert.stdout == ""
  run_once: true
  delegate_to: localhost
  kubernetes.core.k8s:
    state: present
    apply: yes
    definition: "{{ lookup('ansible.builtin.template', 'harbor-tls-cert.yaml.j2') | from_yaml }}"

- name: Install harbor helm chart
  run_once: true
  delegate_to: localhost
  kubernetes.core.helm:
    release_name: harbor
    release_namespace: harbor
    create_namespace: true
    # https://artifacthub.io/packages/helm/harbor/harbor
    chart_ref: ../helm/charts/harbor-1.13.1.tgz
    values: "{{ lookup('ansible.builtin.template', 'values.yaml.j2') | from_yaml }}"
    state: present
    wait: true
