# https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/latest/install-guide.html
---
- name: Check distro
  fail:
    msg: "distro {{ ansible_distribution }} not supported"
  when: ansible_distribution != 'Ubuntu'

- name: Remove nvidia-docker
  ansible.builtin.apt:
    name:
      - nvidia-docker
      - nvidia-docker2
    state: absent

- name: Add NVIDIA Container Toolkit GPG key
  ansible.builtin.shell: |
    curl -fsSL https://nvidia.github.io/libnvidia-container/gpgkey | gpg --yes --dearmor -o /usr/share/keyrings/nvidia-container-toolkit-keyring.gpg \
      && curl -s -L https://nvidia.github.io/libnvidia-container/stable/deb/nvidia-container-toolkit.list | \
      sed 's#deb https://#deb [signed-by=/usr/share/keyrings/nvidia-container-toolkit-keyring.gpg] https://#g' | \
      sudo tee /etc/apt/sources.list.d/nvidia-container-toolkit.list

- name: Install nvidia-container-toolkit
  ansible.builtin.apt:
    name:
      - nvidia-container-toolkit
    state: present
    update_cache: yes

- name: config containerd
  block:
    - name: Configure the container runtime
      ansible.builtin.shell: |
        nvidia-ctk runtime configure --runtime=containerd
      notify: Restart containerd
