---
ansible_user: exaops
ansible_port: 22

ssh_key:
  comment: "exaops@example.com"
  auth_key: guardian
  deploy_key: deploy

host_password:
  example-master-1: "{{ vault_node_password }}"
  example-master-2: "{{ vault_node_password }}"
  example-master-3: "{{ vault_node_password }}"
  example-worker-1: "{{ vault_node_password }}"
  example-worker-2: "{{ vault_node_password }}"
  example-data-1: "{{ vault_node_password }}"

multipass_node: false

cluster:
  name: example
  desc_name: Example
  apex_domain: example.com
  admin_email: exaops@example.com

k8s:
  version: "1.28.4-1.1"
  control_plane_endpoint: cluster-endpoint.k8s.{{ cluster.apex_domain }}

pangu:
  host: example-master-1
  ip: 192.168.100.1
