---
- name: Update ca certificates
  become: true
  ansible.builtin.command: update-ca-certificates

- name: Restart containerd
  ansible.builtin.systemd:
    name: containerd
    daemon_reload: yes
    state: restarted
