---
- hosts: all
  become: yes
  roles:
    - role: infra/hosts
      tags:
        - hosts
    - role: infra/container
      tags:
        - container
    - role: infra/reboot
      tags:
        - reboot
    - role: infra/cert
      tags:
        - cert

- hosts: kube_cluster
  become: yes
  roles:
    - role: k8s/init-node
      tags:
        - init-node
    - role: infra/hostname
      tags:
        - hostname

- hosts: primary_control_planes
  become: yes
  roles:
    - role: k8s/init-cluster
      tags:
        - init-cluster
    - role: k8s/admin-local
      tags:
        - admin-local
    - role: k8s/cni-plugin
      tags:
        - cni-plugin

- hosts: secondary_control_planes
  tags:
    - join
  become: yes
  roles:
    - role: k8s/join-control-plane

- hosts: workers
  tags:
    - join
  become: yes
  roles:
    - role: k8s/join-worker

- hosts: control_planes
  become: yes
  roles:
    - role: k8s/apiserver-port
      tags:
        - apiserver-port
    - role: k8s/control-plane-schedule
      tags:
        - control-plane-schedule
    - role: k8s/gpushare
      tags:
        - gpushare

- hosts: kube_cluster
  tags:
    - nfs-client
  become: yes
  roles:
    - role: infra/nfs-client

- hosts: nfs_server
  become: yes
  roles:
    - role: infra/nfs-server
      tags:
        - nfs-server
    - role: k8s/nfs-pvc
      tags:
        - nfs-pvc

- hosts: gpus
  become: yes
  roles:
    - role: infra/nvidia-cri
      tags:
        - nvidia-cri

- hosts: all
  become: false
  roles:
    - role: k8s/label-node
      tags:
        - label-node
    - role: k8s/coredns
      tags:
        - coredns
    - role: k8s/metrics-server
      tags:
        - metrics-server
    - role: k8s/cert-manager
      tags:
        - cert-manager
    - role: k8s/ingress-nginx
      tags:
        - ingress-nginx
    - role: k8s/dashboard
      tags:
        - dashboard
    - role: k8s/harbor
      tags:
        - harbor
    - role: k8s/mongodb
      tags:
        - mongodb
    - role: k8s/kubevela
      tags:
        - kubevela
